// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVvkFAwQH7wUxr8Wj1jdalP_BGt2tDlvo',
    appId: '1:573899306235:android:b93f9dbe7efd04c4e36c5e',
    messagingSenderId: '573899306235',
    projectId: 'intelli-chat-28',
    storageBucket: 'intelli-chat-28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFhlqTxFKRGBp6EyRPcOM4CfGUE0vIpmI',
    appId: '1:573899306235:ios:503f5c30f6a0f3e8e36c5e',
    messagingSenderId: '573899306235',
    projectId: 'intelli-chat-28',
    storageBucket: 'intelli-chat-28.appspot.com',
    androidClientId: '573899306235-pqqp0km4l8ohootg0ua9asfrn5pl2p6k.apps.googleusercontent.com',
    iosClientId: '573899306235-j3vc5jjhhgo3mfpand4obpnfdpjtntjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.ichat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwFatWihtb3z625leeWg0UXF5NCcEW_bU',
    appId: '1:573899306235:web:69ffa595feff23ece36c5e',
    messagingSenderId: '573899306235',
    projectId: 'intelli-chat-28',
    authDomain: 'intelli-chat-28.firebaseapp.com',
    storageBucket: 'intelli-chat-28.appspot.com',
    measurementId: 'G-WXX9KKEXJT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFhlqTxFKRGBp6EyRPcOM4CfGUE0vIpmI',
    appId: '1:573899306235:ios:503f5c30f6a0f3e8e36c5e',
    messagingSenderId: '573899306235',
    projectId: 'intelli-chat-28',
    storageBucket: 'intelli-chat-28.appspot.com',
    iosClientId: '573899306235-j3vc5jjhhgo3mfpand4obpnfdpjtntjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.ichat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwFatWihtb3z625leeWg0UXF5NCcEW_bU',
    appId: '1:573899306235:web:21069ff9f8b872c4e36c5e',
    messagingSenderId: '573899306235',
    projectId: 'intelli-chat-28',
    authDomain: 'intelli-chat-28.firebaseapp.com',
    storageBucket: 'intelli-chat-28.appspot.com',
    measurementId: 'G-LSW657NY5Z',
  );

}